export const ENV = {
  SUPABASE_URL: process.env.VITE_SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.VITE_SUPABASE_ANON_KEY,
  FOURSQUARE_API_KEY: process.env.VITE_FOURSQUARE_API_KEY,
  UNSPLASH_ACCESS_KEY: process.env.VITE_UNSPLASH_ACCESS_KEY
};